In [2]:
import seaborn as sns
import pandas as pd

iris = sns.load_dataset("iris")
result = iris.loc[:, ['sepal_length', 'species']]
result

# 미션
# 파일명 iris_mission.csv
# dataset 폴더 안으로 해당 파일을 내보내기

     sepal_length    species
0             5.1     setosa
1             4.9     setosa
2             4.7     setosa
3             4.6     setosa
4             5.0     setosa
..            ...        ...
145           6.7  virginica
146           6.3  virginica
147           6.5  virginica
148           6.2  virginica
149           5.9  virginica

[150 rows x 2 columns]

In [7]:
# result.to_csv("상위 폴더로 가기/dataset/iris_result.csv", index=False)
result.to_csv("../dataset/iris_result.csv", index=False)